schemaVersion: 2.2.0
metadata:
  name: frontend-backend-workspace
  version: 2.2.0
projects:
- name: angularui
  git:
    remotes:
      origin: https://github.com/l0rd/che-blog/
    checkoutFrom:
      revision: main
- name: backend
  git:
    remotes:
      origin: https://github.com/l0rd/devworkspace-demo
    checkoutFrom:
      revision: main
commands:
- id: py-cmd-build
  exec:
    commandLine: echo "Done by building img component"
    component: py-ctnr
    workingDir: /projects/Backend/backend
- id: py-cmd-run
  exec:
    commandLine: chmod 0700 /projects/Backend/backend/boot.sh && /projects/Backend/backend/boot.sh
    component: py-ctnr
    workingDir: /projects/Backend/backend
- id: ng-cmd-build
  exec:
    commandLine: npm install && npm install -g @angular/cli
    component: ng-ctnr
    workingDir: /projects/AngularUI
- id: ng-cmd-run
  exec:
    commandLine: /projects/AngularUI/set-backend-route-dev.sh && ng build --configuration=development && ng serve --port 8501 --disable-host-check
    component: ng-ctnr
    workingDir: /projects/AngularUI
- id: py-ng-cmd-build
  composite:
    commands:
      - py-cmd-build
      - ng-cmd-build
    parallel: false
    group:
      kind: build
      isDefault: true
- id: py-ng-cmd-run
  composite:
    commands:
      - py-cmd-run
      - ng-cmd-run
    parallel: true
    group:
      kind: run
      isDefault: true
components:
- name: py-img
  image:
    autoBuild: true
    dockerfile:
      buildContext: /projects
      uri: Backend/backend/Dockerfile
    imageName: quay.io/devfile/universal-developer-image:latest
- name: ng-ctnr
  container:
    args:
    - tail
    - -f
    - /dev/null
    endpoints:
    - name: port-8501-tcp
      protocol: tcp
      targetPort: 8501
    image: registry.access.redhat.com/ubi8/nodejs-18:1-71.1698060565
    memoryLimit: 8Gi
    cpuLimit: '2'
    env:
      - name: DEVSPACE_USERNAME
        value: ${DEVSPACE_USERNAME}
      - name: DEVSPACE_WORKSPACE_NAMES
        value: ${DEVSPACE_WORKSPACE_NAMES}
- name: py-ctnr
  container:
    args:
    - tail
    - -f
    - /dev/null
    endpoints:
    - name: port-8502-tcp
      protocol: tcp
      targetPort: 8502
    image: quay.io/devfile/universal-developer-image:latest
    mountSources: true
