schemaVersion: 2.2.0
metadata:
  name: inventory-quarkus
attributes:
  controller.devfile.io/storage-type: ephemeral
parent:
  uri: https://gist.githubusercontent.com/l0rd/e6d0a4967d3652ec687f76c0e3fbfad9/raw/parent-devfile.yaml
commands:
  - id: buildimage
    exec:
      label: "4. Build Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        # NAMESPACE=openshift
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        IMAGE=image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/quarkus-api-example
        podman build -f src/main/docker/Dockerfile.jvm -t "${IMAGE}" .
      group:
        kind: build
  - id: pushimage
    exec:
      label: "5. Push Image"
      component: tools
      commandLine: |
        # Requires `oc policy add-role-to-user registry-editor <user_name> -n <namespace>`
        # NAMESPACE=openshift
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        IMAGE=image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/quarkus-api-example
        podman login --tls-verify=false -u $(oc whoami) -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000
        podman push --tls-verify=false "${IMAGE}"
      group:
        kind: build
  - id: runpod
    exec:
      label: "6. Run Pod"
      component: tools
      commandLine: |
        # NAMESPACE=openshift
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        IMAGE=image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/quarkus-api-example
        oc run inventory-quarkus --image "${IMAGE}" --port 8080
        oc expose pod/inventory-quarkus
        echo
        echo
        echo "You can now test the application running 'curl -sSL http://inventory-quarkus:8080/api/inventory/100000'"
      group:
        kind: build
  - id: deletepod
    exec:
      label: "7. Delete Pod"
      component: tools
      commandLine: |
        oc delete pod inventory-quarkus &&
        oc delete service inventory-quarkus
      group:
        kind: build
