schemaVersion: 2.2.0
metadata:
  name: inventory-quarkus
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      env:
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: none
          name: test
          protocol: http
          targetPort: 8081
        - exposure: public
          name: inventory
          protocol: http
          targetPort: 8080
          path: /api/inventory/100000
        - name: inventory1
          targetPort: 8081
        - name: inventory2
          targetPort: 8082
        - name: inventory3
          targetPort: 8083
        - name: inventory4
          targetPort: 8084
        - name: inventory5
          targetPort: 8085
        - name: inventory6
          targetPort: 8086
        - name: inventory7
          targetPort: 8087
        - name: inventory8
          targetPort: 8088
        - name: inventory9
          targetPort: 8089
        - name: inventory10
          targetPort: 8090
        - name: inventory11
          targetPort: 8091
        - name: inventory12
          targetPort: 8092
        - name: inventory13
          targetPort: 8093
        - name: inventory14
          targetPort: 8094
        - name: inventory15
          targetPort: 8095
        - name: inventory16
          targetPort: 8096
        - name: inventory17
          targetPort: 8097
        - name: inventory18
          targetPort: 8098
        - name: inventory19
          targetPort: 8099
        - name: inventory20
          targetPort: 8000
      memoryRequest: 5Mi
      memoryLimit: 6G
      cpuRequest: 1000m
      cpuLimit: 4000m
commands:
  - id: package
    exec:
      label: "1. Package"
      component: tools
      workingDir: ${PROJECTS_ROOT}/inventory-quarkus
      commandLine: "./mvnw clean package -DskipTests=true"
      group:
        kind: build
        isDefault: true
  - id: runtests
    exec:
      label: "2. Run Tests"
      component: tools
      workingDir: ${PROJECTS_ROOT}/inventory-quarkus
      commandLine: "./mvnw test"
      group:
        kind: test
  - id: startdev
    exec:
      label: "3. Start Development mode (Hot reload + debug)"
      component: tools
      workingDir: ${PROJECTS_ROOT}/inventory-quarkus
      commandLine: "./mvnw compile quarkus:dev"
      group:
        kind: run
        isDefault: true
  - id: buildimage
    exec:
      label: "4. Build Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        # NAMESPACE=openshift
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        IMAGE=image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/quarkus-api-example
        podman build -f src/main/docker/Dockerfile.jvm -t "${IMAGE}" .
      group:
        kind: build
  - id: pushimage
    exec:
      label: "5. Push Image"
      component: tools
      commandLine: |
        # Requires `oc policy add-role-to-user registry-editor <user_name> -n <namespace>`
        # NAMESPACE=openshift
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        IMAGE=image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/quarkus-api-example
        podman login --tls-verify=false -u $(oc whoami) -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000
        podman push --tls-verify=false "${IMAGE}"
      group:
        kind: build
  - id: runpod
    exec:
      label: "6. Run Pod"
      component: tools
      commandLine: |
        # NAMESPACE=openshift
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        IMAGE=image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/quarkus-api-example
        oc run inventory-quarkus --image "${IMAGE}" --port 8080
        oc expose pod/inventory-quarkus
        echo
        echo
        echo "You can now test the application running 'curl -sSL http://inventory-quarkus:8080/api/inventory/100000'"
      group:
        kind: build
  - id: deletepod
    exec:
      label: "7. Delete Pod"
      component: tools
      commandLine: |
        oc delete pod inventory-quarkus &&
        oc delete service inventory-quarkus
      group:
        kind: build
